In [58]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:\\Users\\Windows 10\\Documents\\DV ASSGINMENT 1 - Muskan Lodha.csv")
print(df)

        Test Response  BCA I  BCA II  BCA III  Unnamed: 5  Unnamed: 6   
0   Pre-Test      Yes    9.0     8.0      6.0         NaN         NaN  \
1  Post-Test      Yes    4.0     5.0      6.0         NaN         NaN   
2   Pre-Test       No   91.0    92.0     94.0         NaN         NaN   
3  Post-Test       No   96.0    95.0     94.0         NaN         NaN   
4        NaN      NaN    NaN     NaN      NaN         NaN         NaN   

   Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  Unnamed: 16  Unnamed: 17   
0         NaN         NaN         NaN  ...          NaN          NaN  \
1         NaN         NaN         NaN  ...          NaN          NaN   
2         NaN         NaN         NaN  ...          NaN          NaN   
3         NaN         NaN         NaN  ...          NaN          NaN   
4         NaN         NaN         NaN  ...          NaN          NaN   

   Unnamed: 18  Unnamed: 19  Unnamed: 20  Unnamed: 21  Unnamed: 22   
0          NaN          NaN          NaN         Test     

In [59]:
x=df[['BCA I','BCA II','BCA III']].values
x

array([[ 9.,  8.,  6.],
       [ 4.,  5.,  6.],
       [91., 92., 94.],
       [96., 95., 94.],
       [nan, nan, nan]])

In [60]:
y=df['Unnamed: 22'].values
y

array(['Response', 'Yes', 'No', 'Yes', 'No'], dtype=object)

In [61]:
from sklearn.impute import SimpleImputer

In [62]:
imputer=SimpleImputer(missing_values=np.NaN,strategy='mean')

In [63]:
imputer=imputer.fit(x[1:5])

In [88]:
x[1:5]=imputer.transform(x[1:25])

In [89]:
x

array([[ 9.,  8.,  6.],
       [ 4.,  5.,  6.],
       [91., 92., 94.],
       [96., 95., 94.],
       [ 4.,  5.,  6.]])

In [90]:
from sklearn.preprocessing import LabelEncoder

In [91]:
label_encoder=LabelEncoder()

In [92]:
y[:0]=label_encoder.fit_transform(y[:0])

In [93]:
y

array([0, 1, 0, 'Yes', 'No'], dtype=object)